precice-config-file: precice-config.xml

participant: Fluid

FSIenabled: true

interfaces:
- mesh: Fluid-Mesh-Centers
  patches:
  - flap
  write-data: Force
- mesh: Fluid-Mesh-Nodes;
  patches:
  - flap
  read-data: Displacement

#FSI
#{
#  rho rho [1 -3 0 0 0 0 0] 1000;
#}