participant: Solid

precice-config-file: precice-config.xml

FSIenabled: true

interfaces:
- mesh: Solid-Mesh-Faces
  patches:
  - wetsurface
  write-data: Force
  
- mesh: Solid-Mesh-Nodes
  patches:
  - wetsurface
  read-data: Displacement

#FSI
#{
#  rho rho [1 -3 0 0 0 0 0] 1000;
#}